{{- if .Values.pink.enabled -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-pink
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name:  {{ .Release.Name }}-pink
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-pink
        app: binder
        component: dind  # Lying to build so current affinity rules can work
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      tolerations:
      - effect: NoSchedule
        key: hub.jupyter.org/dedicated
        operator: Equal
        value: user
      - effect: NoSchedule
        key: hub.jupyter.org_dedicated
        operator: Equal
        value: user
      nodeSelector: {{ .Values.config.BinderHub.build_node_selector | default dict | toJson }}
      {{- with .Values.pink.initContainers }}
      initContainers:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.pink.daemonset.image.pullSecrets }}
      imagePullSecrets:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      securityContext:
        fsGroup: 1000

      containers:
      - name: pink
        image: {{ .Values.pink.daemonset.image.name }}:{{ .Values.pink.daemonset.image.tag }}
        imagePullPolicy: {{ .Values.pink.daemonset.image.pullPolicy }}

        resources:
          {{- .Values.pink.resources | toYaml | nindent 10 }}
        args:
          - podman
          - system
          - service
          - --time=0
          - unix:///var/run/pink/docker.sock
        securityContext:
          privileged: true
          runAsUser: 1000  # podman default user id

        volumeMounts:
        - mountPath: /home/podman/.local/share/containers/storage/
          name: podman-containers
        - mountPath: /var/run/pink/
          name: podman-socket

        {{- with .Values.pink.daemonset.extraVolumeMounts }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
        {{- with .Values.pink.daemonset.lifecycle }}
        lifecycle:
          {{- . | toYaml | nindent 10 }}
        {{- end }}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: podman-containers
        hostPath:
          path: {{ .Values.pink.hostStorageDir }}
          type: Directory
      - name: podman-socket
        hostPath:
          path: {{ .Values.pink.hostSocketDir }}
          type: Directory

      {{- with .Values.pink.daemonset.extraVolumes }}
      {{- . | toYaml | nindent 6 }}
      {{- end }}
{{- end }}
