{{- if ne .Values.imageBuilderType "local" -}}
{{- $builderName := .Values.imageBuilderType }}
{{- $builder := (index .Values $builderName) }}
{{- $daemonset := $builder.daemonset }}

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-{{ $builderName }}
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name:  {{ .Release.Name }}-{{ $builderName }}
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-{{ $builderName }}
        app: binder
        component: image-builder
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      {{- with include "jupyterhub.imagePullSecrets" (dict "root" . "image" $builder.daemonset.image) }}
      imagePullSecrets: {{ . }}
      {{- end }}
      tolerations:
      - effect: NoSchedule
        key: hub.jupyter.org/dedicated
        operator: Equal
        value: user
      - effect: NoSchedule
        key: hub.jupyter.org_dedicated
        operator: Equal
        value: user
      nodeSelector: {{ .Values.config.BinderHub.build_node_selector | default dict | toJson }}

      {{- with $builder.initContainers }}
      initContainers:
        {{- . | toYaml | nindent 8 }}
      {{- end }}

      containers:
        - name: {{ $builderName }}
          image: {{ $daemonset.image.name }}:{{ $daemonset.image.tag }}
          {{- with $daemonset.image.pullPolicy }}
          imagePullPolicy: {{ . }}
          {{- end }}
          {{- with $daemonset.resources }}
          resources:
            {{- $daemonset.resources | toYaml | nindent 12 }}
          {{- end }}
          {{- if eq $builderName "dind" }}
          args:
            - dockerd
            - --storage-driver={{ .Values.dind.storageDriver }}
            - -H unix://{{ .Values.dind.hostSocketDir }}/docker.sock
            {{- with .Values.dind.daemonset.extraArgs }}
            {{- . | toYaml | nindent 12 }}
            {{- end }}
          securityContext:
            privileged: true
          volumeMounts:
          - name: dockerlib-dind
            mountPath: /var/lib/docker
          - name: rundind
            mountPath: {{ $builder.hostSocketDir }}
          {{- end }}
          {{- if eq $builderName "pink" }}
          args:
            - podman
            - system
            - service
            - --time=0
            - unix://{{ .Values.pink.hostSocketDir }}/docker.sock
          securityContext:
            privileged: true
            runAsUser: 0
          volumeMounts:
          - mountPath: /var/lib/containers/storage
            name: podman-containers
          - mountPath: {{ .Values.pink.hostSocketDir }}
            name: podman-socket
          {{- end }}

          {{- with $daemonset.extraVolumeMounts }}
          {{- . | toYaml | nindent 10 }}
          {{- end }}

          {{- with $daemonset.lifecycle }}
          lifecycle:
            {{- . | toYaml | nindent 12 }}
          {{- end }}

      volumes:
        {{- if eq $builderName "dind" }}
        - name: dockerlib-dind
          hostPath:
            path: {{ .Values.dind.hostLibDir }}
            type: DirectoryOrCreate
        - name: rundind
          hostPath:
            path: {{ .Values.dind.hostSocketDir }}
            type: DirectoryOrCreate
        {{- with .Values.dind.daemonset.extraVolumes }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
        {{- end }}
        {{- if eq $builderName "pink" }}
        - name: podman-containers
          hostPath:
            path: {{ .Values.pink.hostStorageDir }}
            type: DirectoryOrCreate
        - name: podman-socket
          hostPath:
            path: {{ .Values.pink.hostSocketDir }}
            type: DirectoryOrCreate
        {{- with .Values.pink.daemonset.extraVolumes }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
        {{- end }}

      terminationGracePeriodSeconds: 30
{{- end }}
